In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from pandas import DataFrame, Series
from sklearn.preprocessing import LabelEncoder
from sklearn import preprocessing
%matplotlib inline

pd.set_option('display.max_rows', 30000)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

df = pd.read_csv('C:/chwweww/dss6_out/sin/train.csv')
print(np.shape(df))
df.tail()

(26729, 10)

      AnimalID  Name             DateTime OutcomeType OutcomeSubtype AnimalType SexuponOutcome AgeuponOutcome                    Breed              Color
26724  A702446   NaN  2015-05-14 11:56:00    Transfer        Partner        Cat    Intact Male        1 month   Domestic Shorthair Mix  Brown Tabby/White
26725  A718934   NaN  2016-01-20 18:59:00    Transfer           SCRP        Cat  Spayed Female       3 months   Domestic Shorthair Mix        Brown Tabby
26726  A698128  Zeus  2015-03-09 13:33:00    Adoption            NaN        Dog  Neutered Male        4 years  Old English Bulldog Mix          White/Tan
26727  A677478   NaN  2014-04-27 12:22:00    Transfer        Partner        Cat    Intact Male        4 weeks   Domestic Shorthair Mix              Black
26728  A706629   NaN  2015-07-02 09:00:00    Transfer           SCRP        Cat    Intact Male         1 year   Domestic Shorthair Mix  Brown Tabby/White

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from pandas import DataFrame, Series
from sklearn.preprocessing import LabelEncoder
from sklearn import preprocessing
%matplotlib inline

pd.set_option('display.max_rows', 30000)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

df = pd.read_csv('C:/chwweww/dss6_out/sin/train.csv')
print(np.shape(df))
df.tail()

(26729, 10)

      AnimalID  Name             DateTime OutcomeType OutcomeSubtype AnimalType SexuponOutcome AgeuponOutcome                    Breed              Color
26724  A702446   NaN  2015-05-14 11:56:00    Transfer        Partner        Cat    Intact Male        1 month   Domestic Shorthair Mix  Brown Tabby/White
26725  A718934   NaN  2016-01-20 18:59:00    Transfer           SCRP        Cat  Spayed Female       3 months   Domestic Shorthair Mix        Brown Tabby
26726  A698128  Zeus  2015-03-09 13:33:00    Adoption            NaN        Dog  Neutered Male        4 years  Old English Bulldog Mix          White/Tan
26727  A677478   NaN  2014-04-27 12:22:00    Transfer        Partner        Cat    Intact Male        4 weeks   Domestic Shorthair Mix              Black
26728  A706629   NaN  2015-07-02 09:00:00    Transfer           SCRP        Cat    Intact Male         1 year   Domestic Shorthair Mix  Brown Tabby/White

In [12]:
df1 = df

In [9]:
from bs4 import BeautifulSoup
import requests
import pandas as pd


info_url = 'http://www.akc.org/public-education/resources/dog-breeds-sorted-groups/'
response = requests.get(info_url)
soup = BeautifulSoup(response.content.decode('latin1'), 'lxml')
breed_group = list()
group_element = list()

groups = soup.select('h2')
for group in groups:
    breed_group.append(group.get_text())


group_element = breed_group
group_element

['HERDING GROUP',
 'HOUND GROUP',
 'TOY GROUP',
 'NON-SPORTING GROUP',
 'SPORTING GROUP',
 'TERRIER GROUP',
 'WORKING GROUP',
 'MISCELLANEOUS CLASS']

In [10]:
group_lists = soup.select('ol')
dog_list = list()
for num,group_list in enumerate(group_lists):
    group_lst = group_list.select('li')
    breed_group[num] = list()
    for dog_breeds in group_lst:
        dog_breed = dog_breeds.find('a')
        breed_group[num].append(dog_breed.get_text())

In [23]:
df_HERDING = pd.DataFrame(breed_group[0], columns=['Breed'])
df_HERDING["GROUP"] = "HERDING GROUP"

df_HOUND = pd.DataFrame(breed_group[1], columns=['Breed'])
df_HOUND["GROUP"] = "HOUND GROUP"

df_TOY = pd.DataFrame(breed_group[2], columns=['Breed'])
df_TOY["GROUP"] = "TOY GROUP"

df_NON_SPORTING = pd.DataFrame(breed_group[3] , columns=['Breed'])
df_NON_SPORTING["GROUP"] = "NON-SPORTING GROUP"

df_SPORTING = pd.DataFrame(breed_group[4], columns=['Breed'])
df_SPORTING["GROUP"] = "SPORTING GROUP"

df_TERRIER = pd.DataFrame(breed_group[5], columns=['Breed'])
df_TERRIER["GROUP"] = "TERRIER GROUP"

df_WORKING = pd.DataFrame(breed_group[6], columns=['Breed'])
df_WORKING["GROUP"] = "WORKING GROUP"

df_MISCELLANEOUS = pd.DataFrame(breed_group[7], columns=['Breed'])
df_MISCELLANEOUS["GROUP"] = "MISCELLANEOUS CLASS"

In [24]:
df_group_all = pd.concat([df_HERDING, df_HOUND , df_NON_SPORTING , df_SPORTING ,df_TERRIER , df_WORKING , df_MISCELLANEOUS], axis=0)
df_group_all

                                 Breed                GROUP
0                Australian Cattle Dog        HERDING GROUP
1                  Australian Shepherd        HERDING GROUP
2                       Bearded Collie        HERDING GROUP
3                            Beauceron        HERDING GROUP
4                     Belgian Malinois        HERDING GROUP
5                     Belgian Sheepdog        HERDING GROUP
6                     Belgian Tervuren        HERDING GROUP
7                           Bergamasco        HERDING GROUP
8                        Berger Picard        HERDING GROUP
9                        Border Collie        HERDING GROUP
10                Bouvier des Flandres        HERDING GROUP
11                              Briard        HERDING GROUP
12                          Canaan Dog        HERDING GROUP
13                Cardigan Welsh Corgi        HERDING GROUP
14                              Collie        HERDING GROUP
15             Entlebucher Moutain Dog        HERDING GROUP
16                    Finnish Lapphund        HERDING GROUP
17                 German Shepherd Dog        HERDING GROUP
18                  Icelandic Sheepdog        HERDING GROUP
19         Miniature American Shepherd        HERDING GROUP
20                    Norwegian Buhund        HERDING GROUP
21                Old English Sheepdog        HERDING GROUP
22                Pembroke Welsh Corgi        HERDING GROUP
23             Polish Lowland Sheepdog        HERDING GROUP
24                                Puli        HERDING GROUP
25                                Pumi        HERDING GROUP
26                   Pyrenean Sheepdog        HERDING GROUP
27                   Shetland Sheepdog        HERDING GROUP
28                   Spanish Water Dog        HERDING GROUP
29                    Swedish Vallhund        HERDING GROUP
0                         Afghan Hound          HOUND GROUP
1           American English Coonhound          HOUND GROUP
2                    American Foxhound          HOUND GROUP
3                              Basenji          HOUND GROUP
4                         Basset Hound          HOUND GROUP
5                               Beagle          HOUND GROUP
6              Black and Tan Coonhound          HOUND GROUP
7                           Bloodhound          HOUND GROUP
8                   Bluetick Coonhound          HOUND GROUP
9                               Borzoi          HOUND GROUP
10                   Cirneco Dell’Etna          HOUND GROUP
11                           Dachshund          HOUND GROUP
12                    English Foxhound          HOUND GROUP
13                           Greyhound          HOUND GROUP
14                             Harrier          HOUND GROUP
15                        Ibizan Hound          HOUND GROUP
16                     Irish Wolfhound          HOUND GROUP
17                  Norwegian Elkhound          HOUND GROUP
18                          Otterhound          HOUND GROUP
19        Petit Basset Griffon Vendeen          HOUND GROUP
20                       Pharaoh Hound          HOUND GROUP
21                               Plott          HOUND GROUP
22          Portuguese Podengo Pequeno          HOUND GROUP
23                   Redbone Coonhound          HOUND GROUP
24                 Rhodesian Ridgeback          HOUND GROUP
25                              Saluki          HOUND GROUP
26                  Scottish Deerhound          HOUND GROUP
27                             Sloughi          HOUND GROUP
28            Treeing Walker Coonhound          HOUND GROUP
29                             Whippet          HOUND GROUP
0                  American Eskimo Dog   NON-SPORTING GROUP
1                         Bichon Frise   NON-SPORTING GROUP
2                       Boston Terrier   NON-SPORTING GROUP
3                              Bulldog   NON-SPORTING GROUP
4                     Chinese Shar-Pei   NON-SPORTING GROUP
5                            Chow Chow   NON-SPORTING GROUP
6                      Coton De Tulear   NON-SPORTING GROUP
7                            Dalmatian   NON-SPORTING GROUP
8                         Finish Spitz   NON-SPORTING GROUP
9                       French Bulldog   NON-SPORTING GROUP
10                            Keeshond   NON-SPORTING GROUP
11                          Lhasa Apso   NON-SPORTING GROUP
12                             Lowchen   NON-SPORTING GROUP
13                  Norwegian Lundhund   NON-SPORTING GROUP
14                              Poodle   NON-SPORTING GROUP
15                          Schipperke   NON-SPORTING GROUP
16                           Shiba Inu   NON-SPORTING GROUP
17                     Tibetan Spaniel   NON-SPORTING GROUP
18                     Tibetan Terrier   NON-SPORTING GROUP
19                      Xoloitzcuintli   NON-SPORTING GROUP
0               American Water Spaniel       SPORTING GROUP
1                       Boykin Spaniel       SPORTING GROUP
2                             Brittany       SPORTING GROUP
3             Chesapeake Bay Retriever       SPORTING GROUP
4                      Clumber Spaniel       SPORTING GROUP
5                       Cocker Spaniel       SPORTING GROUP
6               Curly-Coated Retriever       SPORTING GROUP
7               English Cocker Spaniel       SPORTING GROUP
8                       English Setter       SPORTING GROUP
9             English Springer Spaniel       SPORTING GROUP
10                       Field Spaniel       SPORTING GROUP
11               Flat-Coated Retriever       SPORTING GROUP
12          German Shorthaired Pointer       SPORTING GROUP
13           German Wirehaired Pointer       SPORTING GROUP
14                    Golden Retriever       SPORTING GROUP
15                       Gordon Setter       SPORTING GROUP
16          Irish Red and White Setter       SPORTING GROUP
17                        Irish Setter       SPORTING GROUP
18                 Irish Water Spaniel       SPORTING GROUP
19                  Labrador Retriever       SPORTING GROUP
20                   Lagotto Romagnolo       SPORTING GROUP
21  Nova Scotia Duck Tolling Retriever       SPORTING GROUP
22                             Pointer       SPORTING GROUP
23                    Spinone Italiano       SPORTING GROUP
24                      Sussex Spaniel       SPORTING GROUP
25                              Vizsla       SPORTING GROUP
26                          Weimaraner       SPORTING GROUP
27              Welsh Springer Spaniel       SPORTING GROUP
28         Wirehaired Pointing Griffon       SPORTING GROUP
29                   Wirehaired Vizsla       SPORTING GROUP
0                     Airedale Terrier        TERRIER GROUP
1            American Hairless Terrier        TERRIER GROUP
2       American Staffordshire Terrier        TERRIER GROUP
3                   Australian Terrier        TERRIER GROUP
4                   Bedlington Terrier        TERRIER GROUP
5                       Border Terrier        TERRIER GROUP
6                         Bull Terrier        TERRIER GROUP
7                        Cairn Terrier        TERRIER GROUP
8                        Cesky Terrier        TERRIER GROUP
9               Dandie Dinmont Terrier        TERRIER GROUP
10               Glen of Imaal Terrier        TERRIER GROUP
11                       Irish Terrier        TERRIER GROUP
12                  Kerry Blue Terrier        TERRIER GROUP
13                    Lakeland Terrier        TERRIER GROUP
14                  Manchester Terrier        TERRIER GROUP
15              Miniature Bull Terrier        TERRIER GROUP
16                 Miniature Schnauzer        TERRIER GROUP
17                     Norfolk Terrier        TERRIER GROUP
18                     Norwich Terrier        TERRIER GROUP
19              Parson Russell Terrier        TERRIER GROUP
20                         Rat Terrier        TERRIER GROUP
21                     Russell Terrier        TERRIER GROUP
22                    Scottish Terrier        TERRIER GROUP
23                    Sealyham Terrier        TERRIER GROUP
24                        Skye Terrier        TERRIER GROUP
25                  Smooth Fox Terrier        TERRIER GROUP
26          Staffordshire Bull Terrier        TERRIER GROUP
27                       Welsh Terrier        TERRIER GROUP
28         West Highland White Terrier        TERRIER GROUP
29                    Wire Fox Terrier        TERRIER GROUP
0                                Akita        WORKING GROUP
1                     Alaskan Malamute        WORKING GROUP
2               Anatolian Shepherd Dog        WORKING GROUP
3                 Bernese Mountain Dog        WORKING GROUP
4                Black Russian Terrier        WORKING GROUP
5                             Boerboel        WORKING GROUP
6                                Boxer        WORKING GROUP
7                          Bullmastiff        WORKING GROUP
8                           Cane Corso        WORKING GROUP
9                              Chinook        WORKING GROUP
10                   Doberman Pinscher        WORKING GROUP
11                   Dogue de Bordeaux        WORKING GROUP
12                     German Pinscher        WORKING GROUP
13                     Giant Schnauzer        WORKING GROUP
14                          Great Dane        WORKING GROUP
15                      Great Pyrenees        WORKING GROUP
16          Greater Swiss Mountain Dog        WORKING GROUP
17                            Komondor        WORKING GROUP
18                              Kuvasz        WORKING GROUP
19                          Leonberger        WORKING GROUP
20                             Mastiff        WORKING GROUP
21                  Neapolitan Mastiff        WORKING GROUP
22                        Newfoundland        WORKING GROUP
23                Portuguese Water Dog        WORKING GROUP
24                          Rottweiler        WORKING GROUP
25                             Samoyed        WORKING GROUP
26                      Siberian Husky        WORKING GROUP
27                  Standard Schnauzer        WORKING GROUP
28                     Tibetan Mastiff        WORKING GROUP
29                         St. Bernard        WORKING GROUP
0                              Azawakh  MISCELLANEOUS CLASS
1                    Belgian Laekenois  MISCELLANEOUS CLASS
2                       Dogo Argentino  MISCELLANEOUS CLASS
3         Grand Basset Griffon Vendeen  MISCELLANEOUS CLASS
4            Nederlandse Kooikerhondje  MISCELLANEOUS CLASS
5                      Norrbottenspets  MISCELLANEOUS CLASS
6                 Peruvian Inca Orchid  MISCELLANEOUS CLASS
7                   Portuguese Podengo  MISCELLANEOUS CLASS

In [12]:
df1 = df

In [9]:
from bs4 import BeautifulSoup
import requests
import pandas as pd


info_url = 'http://www.akc.org/public-education/resources/dog-breeds-sorted-groups/'
response = requests.get(info_url)
soup = BeautifulSoup(response.content.decode('latin1'), 'lxml')
breed_group = list()
group_element = list()

groups = soup.select('h2')
for group in groups:
    breed_group.append(group.get_text())


group_element = breed_group
group_element

['HERDING GROUP',
 'HOUND GROUP',
 'TOY GROUP',
 'NON-SPORTING GROUP',
 'SPORTING GROUP',
 'TERRIER GROUP',
 'WORKING GROUP',
 'MISCELLANEOUS CLASS']

In [10]:
group_lists = soup.select('ol')
dog_list = list()
for num,group_list in enumerate(group_lists):
    group_lst = group_list.select('li')
    breed_group[num] = list()
    for dog_breeds in group_lst:
        dog_breed = dog_breeds.find('a')
        breed_group[num].append(dog_breed.get_text())

In [23]:
df_HERDING = pd.DataFrame(breed_group[0], columns=['Breed'])
df_HERDING["GROUP"] = "HERDING GROUP"

df_HOUND = pd.DataFrame(breed_group[1], columns=['Breed'])
df_HOUND["GROUP"] = "HOUND GROUP"

df_TOY = pd.DataFrame(breed_group[2], columns=['Breed'])
df_TOY["GROUP"] = "TOY GROUP"

df_NON_SPORTING = pd.DataFrame(breed_group[3] , columns=['Breed'])
df_NON_SPORTING["GROUP"] = "NON-SPORTING GROUP"

df_SPORTING = pd.DataFrame(breed_group[4], columns=['Breed'])
df_SPORTING["GROUP"] = "SPORTING GROUP"

df_TERRIER = pd.DataFrame(breed_group[5], columns=['Breed'])
df_TERRIER["GROUP"] = "TERRIER GROUP"

df_WORKING = pd.DataFrame(breed_group[6], columns=['Breed'])
df_WORKING["GROUP"] = "WORKING GROUP"

df_MISCELLANEOUS = pd.DataFrame(breed_group[7], columns=['Breed'])
df_MISCELLANEOUS["GROUP"] = "MISCELLANEOUS CLASS"

In [24]:
df_group_all = pd.concat([df_HERDING, df_HOUND , df_NON_SPORTING , df_SPORTING ,df_TERRIER , df_WORKING , df_MISCELLANEOUS], axis=0)
df_group_all

                                 Breed                GROUP
0                Australian Cattle Dog        HERDING GROUP
1                  Australian Shepherd        HERDING GROUP
2                       Bearded Collie        HERDING GROUP
3                            Beauceron        HERDING GROUP
4                     Belgian Malinois        HERDING GROUP
5                     Belgian Sheepdog        HERDING GROUP
6                     Belgian Tervuren        HERDING GROUP
7                           Bergamasco        HERDING GROUP
8                        Berger Picard        HERDING GROUP
9                        Border Collie        HERDING GROUP
10                Bouvier des Flandres        HERDING GROUP
11                              Briard        HERDING GROUP
12                          Canaan Dog        HERDING GROUP
13                Cardigan Welsh Corgi        HERDING GROUP
14                              Collie        HERDING GROUP
15             Entlebucher Moutain Dog        HERDING GROUP
16                    Finnish Lapphund        HERDING GROUP
17                 German Shepherd Dog        HERDING GROUP
18                  Icelandic Sheepdog        HERDING GROUP
19         Miniature American Shepherd        HERDING GROUP
20                    Norwegian Buhund        HERDING GROUP
21                Old English Sheepdog        HERDING GROUP
22                Pembroke Welsh Corgi        HERDING GROUP
23             Polish Lowland Sheepdog        HERDING GROUP
24                                Puli        HERDING GROUP
25                                Pumi        HERDING GROUP
26                   Pyrenean Sheepdog        HERDING GROUP
27                   Shetland Sheepdog        HERDING GROUP
28                   Spanish Water Dog        HERDING GROUP
29                    Swedish Vallhund        HERDING GROUP
0                         Afghan Hound          HOUND GROUP
1           American English Coonhound          HOUND GROUP
2                    American Foxhound          HOUND GROUP
3                              Basenji          HOUND GROUP
4                         Basset Hound          HOUND GROUP
5                               Beagle          HOUND GROUP
6              Black and Tan Coonhound          HOUND GROUP
7                           Bloodhound          HOUND GROUP
8                   Bluetick Coonhound          HOUND GROUP
9                               Borzoi          HOUND GROUP
10                   Cirneco Dell’Etna          HOUND GROUP
11                           Dachshund          HOUND GROUP
12                    English Foxhound          HOUND GROUP
13                           Greyhound          HOUND GROUP
14                             Harrier          HOUND GROUP
15                        Ibizan Hound          HOUND GROUP
16                     Irish Wolfhound          HOUND GROUP
17                  Norwegian Elkhound          HOUND GROUP
18                          Otterhound          HOUND GROUP
19        Petit Basset Griffon Vendeen          HOUND GROUP
20                       Pharaoh Hound          HOUND GROUP
21                               Plott          HOUND GROUP
22          Portuguese Podengo Pequeno          HOUND GROUP
23                   Redbone Coonhound          HOUND GROUP
24                 Rhodesian Ridgeback          HOUND GROUP
25                              Saluki          HOUND GROUP
26                  Scottish Deerhound          HOUND GROUP
27                             Sloughi          HOUND GROUP
28            Treeing Walker Coonhound          HOUND GROUP
29                             Whippet          HOUND GROUP
0                  American Eskimo Dog   NON-SPORTING GROUP
1                         Bichon Frise   NON-SPORTING GROUP
2                       Boston Terrier   NON-SPORTING GROUP
3                              Bulldog   NON-SPORTING GROUP
4                     Chinese Shar-Pei   NON-SPORTING GROUP
5                            Chow Chow   NON-SPORTING GROUP
6                      Coton De Tulear   NON-SPORTING GROUP
7                            Dalmatian   NON-SPORTING GROUP
8                         Finish Spitz   NON-SPORTING GROUP
9                       French Bulldog   NON-SPORTING GROUP
10                            Keeshond   NON-SPORTING GROUP
11                          Lhasa Apso   NON-SPORTING GROUP
12                             Lowchen   NON-SPORTING GROUP
13                  Norwegian Lundhund   NON-SPORTING GROUP
14                              Poodle   NON-SPORTING GROUP
15                          Schipperke   NON-SPORTING GROUP
16                           Shiba Inu   NON-SPORTING GROUP
17                     Tibetan Spaniel   NON-SPORTING GROUP
18                     Tibetan Terrier   NON-SPORTING GROUP
19                      Xoloitzcuintli   NON-SPORTING GROUP
0               American Water Spaniel       SPORTING GROUP
1                       Boykin Spaniel       SPORTING GROUP
2                             Brittany       SPORTING GROUP
3             Chesapeake Bay Retriever       SPORTING GROUP
4                      Clumber Spaniel       SPORTING GROUP
5                       Cocker Spaniel       SPORTING GROUP
6               Curly-Coated Retriever       SPORTING GROUP
7               English Cocker Spaniel       SPORTING GROUP
8                       English Setter       SPORTING GROUP
9             English Springer Spaniel       SPORTING GROUP
10                       Field Spaniel       SPORTING GROUP
11               Flat-Coated Retriever       SPORTING GROUP
12          German Shorthaired Pointer       SPORTING GROUP
13           German Wirehaired Pointer       SPORTING GROUP
14                    Golden Retriever       SPORTING GROUP
15                       Gordon Setter       SPORTING GROUP
16          Irish Red and White Setter       SPORTING GROUP
17                        Irish Setter       SPORTING GROUP
18                 Irish Water Spaniel       SPORTING GROUP
19                  Labrador Retriever       SPORTING GROUP
20                   Lagotto Romagnolo       SPORTING GROUP
21  Nova Scotia Duck Tolling Retriever       SPORTING GROUP
22                             Pointer       SPORTING GROUP
23                    Spinone Italiano       SPORTING GROUP
24                      Sussex Spaniel       SPORTING GROUP
25                              Vizsla       SPORTING GROUP
26                          Weimaraner       SPORTING GROUP
27              Welsh Springer Spaniel       SPORTING GROUP
28         Wirehaired Pointing Griffon       SPORTING GROUP
29                   Wirehaired Vizsla       SPORTING GROUP
0                     Airedale Terrier        TERRIER GROUP
1            American Hairless Terrier        TERRIER GROUP
2       American Staffordshire Terrier        TERRIER GROUP
3                   Australian Terrier        TERRIER GROUP
4                   Bedlington Terrier        TERRIER GROUP
5                       Border Terrier        TERRIER GROUP
6                         Bull Terrier        TERRIER GROUP
7                        Cairn Terrier        TERRIER GROUP
8                        Cesky Terrier        TERRIER GROUP
9               Dandie Dinmont Terrier        TERRIER GROUP
10               Glen of Imaal Terrier        TERRIER GROUP
11                       Irish Terrier        TERRIER GROUP
12                  Kerry Blue Terrier        TERRIER GROUP
13                    Lakeland Terrier        TERRIER GROUP
14                  Manchester Terrier        TERRIER GROUP
15              Miniature Bull Terrier        TERRIER GROUP
16                 Miniature Schnauzer        TERRIER GROUP
17                     Norfolk Terrier        TERRIER GROUP
18                     Norwich Terrier        TERRIER GROUP
19              Parson Russell Terrier        TERRIER GROUP
20                         Rat Terrier        TERRIER GROUP
21                     Russell Terrier        TERRIER GROUP
22                    Scottish Terrier        TERRIER GROUP
23                    Sealyham Terrier        TERRIER GROUP
24                        Skye Terrier        TERRIER GROUP
25                  Smooth Fox Terrier        TERRIER GROUP
26          Staffordshire Bull Terrier        TERRIER GROUP
27                       Welsh Terrier        TERRIER GROUP
28         West Highland White Terrier        TERRIER GROUP
29                    Wire Fox Terrier        TERRIER GROUP
0                                Akita        WORKING GROUP
1                     Alaskan Malamute        WORKING GROUP
2               Anatolian Shepherd Dog        WORKING GROUP
3                 Bernese Mountain Dog        WORKING GROUP
4                Black Russian Terrier        WORKING GROUP
5                             Boerboel        WORKING GROUP
6                                Boxer        WORKING GROUP
7                          Bullmastiff        WORKING GROUP
8                           Cane Corso        WORKING GROUP
9                              Chinook        WORKING GROUP
10                   Doberman Pinscher        WORKING GROUP
11                   Dogue de Bordeaux        WORKING GROUP
12                     German Pinscher        WORKING GROUP
13                     Giant Schnauzer        WORKING GROUP
14                          Great Dane        WORKING GROUP
15                      Great Pyrenees        WORKING GROUP
16          Greater Swiss Mountain Dog        WORKING GROUP
17                            Komondor        WORKING GROUP
18                              Kuvasz        WORKING GROUP
19                          Leonberger        WORKING GROUP
20                             Mastiff        WORKING GROUP
21                  Neapolitan Mastiff        WORKING GROUP
22                        Newfoundland        WORKING GROUP
23                Portuguese Water Dog        WORKING GROUP
24                          Rottweiler        WORKING GROUP
25                             Samoyed        WORKING GROUP
26                      Siberian Husky        WORKING GROUP
27                  Standard Schnauzer        WORKING GROUP
28                     Tibetan Mastiff        WORKING GROUP
29                         St. Bernard        WORKING GROUP
0                              Azawakh  MISCELLANEOUS CLASS
1                    Belgian Laekenois  MISCELLANEOUS CLASS
2                       Dogo Argentino  MISCELLANEOUS CLASS
3         Grand Basset Griffon Vendeen  MISCELLANEOUS CLASS
4            Nederlandse Kooikerhondje  MISCELLANEOUS CLASS
5                      Norrbottenspets  MISCELLANEOUS CLASS
6                 Peruvian Inca Orchid  MISCELLANEOUS CLASS
7                   Portuguese Podengo  MISCELLANEOUS CLASS

In [53]:
df_all_1 = pd.merge(df_all , df_group_all , how='left')

In [55]:
df_all_1.head()

  AnimalID     Name             DateTime      OutcomeType OutcomeSubtype AnimalType SexuponOutcome AgeuponOutcome               Breed        Color  BreedMix               GROUP
0  A671945  Hambone  2014-02-12 18:22:00  Return_to_owner            NaN        Dog  Neutered Male         1 year   Shetland Sheepdog  Brown/White         1       HERDING GROUP
1  A656520    Emily  2013-10-13 12:44:00       Euthanasia      Suffering        Cat  Spayed Female         1 year  Domestic Shorthair  Cream Tabby         1                 NaN
2  A686464   Pearce  2015-01-31 12:28:00         Adoption         Foster        Dog  Neutered Male        2 years            Pit Bull   Blue/White         1                 NaN
3  A683430      NaN  2014-07-11 19:09:00         Transfer        Partner        Cat    Intact Male        3 weeks  Domestic Shorthair   Blue Cream         1                 NaN
4  A667013      NaN  2013-11-15 12:52:00         Transfer        Partner        Dog  Neutered Male        2 years          Lhasa Apso          Tan         1  NON-SPORTING GROUP

In [65]:
print(df_all_1.shape)

(26729, 12)

In [62]:
df_all_1.groupby([ 'AnimalType', 'GROUP']).count()

                                AnimalID  Name  DateTime  OutcomeType  OutcomeSubtype  SexuponOutcome  AgeuponOutcome  Breed  Color  BreedMix
AnimalType GROUP
Dog        HERDING GROUP            1275  1056      1275         1275             426            1275            1275   1275   1275      1275
           HOUND GROUP               947   782       947          947             338             946             947    947    947       947
           MISCELLANEOUS CLASS        17    17        17           17              10              17              17     17     17        17
           NON-SPORTING GROUP        343   273       343          343             134             343             343    343    343       343
           SPORTING GROUP           2329  1895      2329         2329             818            2329            2329   2329   2329      2329
           TERRIER GROUP             947   753       947          947             298             947             947    947    947       947
           WORKING GROUP            1059   938      1059         1059             345            1059            1059   1059   1059      1059

In [67]:
df_jo = df_all_1.copy()

In [77]:
df_jo['GROUP'].fillna("unknown", inplace=True)

In [83]:
df_jo.groupby(['AnimalType','Breed', 'GROUP']).count()

                                                                   AnimalID  Name  DateTime  OutcomeType  OutcomeSubtype  SexuponOutcome  AgeuponOutcome  Color  BreedMix
AnimalType Breed                              GROUP
Cat        Abyssinian                         unknown                     2     2         2            2               0               2               2      2         2
           American Shorthair                 unknown                     9     6         9            9               8               9               9      9         9
           Angora                             unknown                     7     5         7            7               3               7               7      7         7
           Balinese                           unknown                     5     5         5            5               4               5               5      5         5
           Bengal                             unknown                     5     4         5            5               1               5               5      5         5
           Bombay                             unknown                     5     5         5            5               1               5               5      5         5
           British Shorthair                  unknown                     4     4         4            4               2               4               4      4         4
           Burmese                            unknown                     1     0         1            1               0               1               1      1         1
           Cornish Rex                        unknown                     1     1         1            1               0               1               1      1         1
           Cymric                             unknown                     2     2         2            2               2               2               2      2         2
           Devon Rex                          unknown                     2     2         2            2               1               2               2      2         2
           Domestic Longhair                  unknown                   547   351       547          547             339             547             546    547       547
           Domestic Medium Hair               unknown                   883   517       883          883             606             883             883    883       883
           Domestic Shorthair                 unknown                  8958  4741      8958         8958            6130            8958            8942   8958      8958
           Exotic Shorthair                   unknown                     2     2         2            2               2               2               2      2         2
           Havana Brown                       unknown                     1     1         1            1               1               1               1      1         1
           Himalayan                          unknown                    18    12        18           18              10              18              18     18        18
           Japanese Bobtail                   unknown                     6     5         6            6               4               6               6      6         6
           Javanese                           unknown                     2     2         2            2               0               2               2      2         2
           Maine Coon                         unknown                    47    39        47           47              23              47              47     47        47
           Manx                               unknown                    48    34        48           48              27              48              48     48        48
           Munchkin Longhair                  unknown                     1     0         1            1               1               1               1      1         1
           Norwegian Forest Cat               unknown                     1     1         1            1               1               1               1      1         1
           Ocicat                             unknown                     1     1         1            1               0               1               1      1         1
           Persian                            unknown                    14    10        14           14               7              14              14     14        14
           Pixiebob Shorthair                 unknown                     3     3         3            3               2               3               3      3         3
           Ragdoll                            unknown                    12     6        12           12               9              12              12     12        12
           Russian Blue                       unknown                    35    28        35           35              17              35              35     35        35
           Siamese                            unknown                   426   262       426          426             260             426             426    426       426
           Snowshoe                           unknown                    78    58        78           78              45              78              78     78        78
           Sphynx                             unknown                     2     2         2            2               1               2               2      2         2
           Tonkinese                          unknown                     4     2         4            4               3               4               4      4         4
           Turkish Van                        unknown                     2     2         2            2               1               2               2      2         2
Dog        Affenpinscher                      unknown                     6     6         6            6               1               6               6      6         6
           Afghan Hound                       HOUND GROUP                 1     1         1            1               0               1               1      1         1
           Airedale Terrier                   TERRIER GROUP               8     7         8            8               4               8               8      8         8
           Akita                              WORKING GROUP              21    20        21           21               6              21              21     21        21
           Alaskan Husky                      unknown                    16    15        16           16               4              16              16     16        16
           Alaskan Malamute                   WORKING GROUP              11    11        11           11               1              11              11     11        11
           American Bulldog                   unknown                   130   114       130          130              51             130             130    130       130
           American Eskimo                    unknown                    14    13        14           14               4              14              14     14        14
           American Foxhound                  HOUND GROUP                 5     5         5            5               0               5               5      5         5
           American Pit Bull Terrier          unknown                    83    76        83           83              29              83              83     83        83
           American Staffordshire Terrier     TERRIER GROUP             110    99       110          110              37             110             110    110       110
           Anatol Shepherd                    unknown                   118    95       118          118              43             118             118    118       118
           Australian Cattle Dog              HERDING GROUP             511   424       511          511             177             511             511    511       511
           Australian Kelpie                  unknown                   116    89       116          116              48             116             116    116       116
           Australian Shepherd                HERDING GROUP             229   184       229          229              71             229             229    229       229
           Australian Terrier                 TERRIER GROUP               4     3         4            4               0               4               4      4         4
           Basenji                            HOUND GROUP                18    18        18           18               5              18              18     18        18
           Basset Hound                       HOUND GROUP                71    65        71           71              15              71              71     71        71
           Beagle                             HOUND GROUP               220   190       220          220              65             220             220    220       220
           Bearded Collie                     HERDING GROUP               2     2         2            2               1               2               2      2         2
           Beauceron                          HERDING GROUP              12    10        12           12               6              12              12     12        12
           Bedlington Terr                    unknown                     3     3         3            3               0               3               3      3         3
           Belgian Malinois                   HERDING GROUP              18    15        18           18               5              18              18     18        18
           Belgian Sheepdog                   HERDING GROUP               3     2         3            3               0               3               3      3         3
           Belgian Tervuren                   HERDING GROUP               2     2         2            2               2               2               2      2         2
           Bernese Mountain Dog               WORKING GROUP               9     8         9            9               2               9               9      9         9
           Bichon Frise                       NON-SPORTING GROUP         20    14        20           20               3              20              20     20        20
           Black                              unknown                    25    21        25           25               8              25              25     25        25
           Black Mouth Cur                    unknown                    89    80        89           89              19              89              89     89        89
           Bloodhound                         HOUND GROUP                 8     7         8            8               1               8               8      8         8
           Blue Lacy                          unknown                    59    48        59           59              18              59              59     59        59
           Bluetick Hound                     unknown                     7     6         7            7               1               7               7      7         7
           Boerboel                           WORKING GROUP               4     4         4            4               1               4               4      4         4
           Border Collie                      HERDING GROUP             334   283       334          334             111             334             334    334       334
           Border Terrier                     TERRIER GROUP              53    43        53           53              12              53              53     53        53
           Boston Terrier                     NON-SPORTING GROUP         67    50        67           67              25              67              67     67        67
           Boxer                              WORKING GROUP             360   315       360          360             132             360             360    360       360
           Boykin Span                        unknown                     4     3         4            4               1               4               4      4         4
           Brittany                           SPORTING GROUP             11    11        11           11               2              11              11     11        11
           Bruss Griffon                      unknown                    26    21        26           26               9              26              26     26        26
           Bull Terrier                       TERRIER GROUP              38    33        38           38              16              38              38     38        38
           Bull Terrier Miniature             unknown                     3     3         3            3               1               3               3      3         3
           Bulldog                            NON-SPORTING GROUP         14    14        14           14               2              14              14     14        14
           Bullmastiff                        WORKING GROUP              11    11        11           11               2              11              11     11        11
           Cairn Terrier                      TERRIER GROUP             142    97       142          142              47             142             142    142       142
           Canaan Dog                         HERDING GROUP               5     5         5            5               2               5               5      5         5
           Cane Corso                         WORKING GROUP               8     8         8            8               1               8               8      8         8
           Cardigan Welsh Corgi               HERDING GROUP              84    67        84           84              29              84              84     84        84
           Carolina Dog                       unknown                    48    39        48           48              23              48              48     48        48
           Catahoula                          unknown                   218   190       218          218              77             218             218    218       218
           Cavalier Span                      unknown                    12     8        12           12               2              12              12     12        12
           Chesa Bay Retr                     unknown                    13    12        13           13               4              13              13     13        13
           Chihuahua Longhair                 unknown                   168   132       168          168              56             168             168    168       168
           Chihuahua Shorthair                unknown                  2145  1723      2145         2145             844            2145            2145   2145      2145
           Chinese Crested                    unknown                     5     5         5            5               2               5               5      5         5
           Chinese Sharpei                    unknown                    43    35        43           43              23              43              43     43        43
           Chow Chow                          NON-SPORTING GROUP         95    72        95           95              41              95              95     95        95
           Cocker Spaniel                     SPORTING GROUP             84    66        84           84              34              84              84     84        84
           Collie Rough                       unknown                    19    16        19           19               5              19              19     19        19
           Collie Smooth                      unknown                    43    36        43           43              13              43              43     43        43
           Dachshund                          HOUND GROUP               510   395       510          510             209             509             510    510       510
           Dachshund Longhair                 unknown                    54    37        54           54              18              54              54     54        54
           Dachshund Wirehair                 unknown                    56    43        56           56              22              56              56     56        56
           Dalmatian                          NON-SPORTING GROUP         17    15        17           17               3              17              17     17        17
           Doberman Pinsch                    unknown                    71    64        71           71              29              71              71     71        71
           Dogo Argentino                     MISCELLANEOUS CLASS        17    17        17           17              10              17              17     17        17
           Dogue De Bordeaux                  unknown                     5     5         5            5               2               5               5      5         5
           Dutch Shepherd                     unknown                     9     8         9            9               4               9               9      9         9
           English Bulldog                    unknown                    43    38        43           43               9              43              43     43        43
           English Cocker Spaniel             SPORTING GROUP              1     1         1            1               1               1               1      1         1
           English Coonhound                  unknown                     8     7         8            8               3               8               8      8         8
           English Foxhound                   HOUND GROUP                 3     3         3            3               1               3               3      3         3
           English Pointer                    unknown                    15    14        15           15               6              15              15     15        15
           English Setter                     SPORTING GROUP              2     2         2            2               1               2               2      2         2
           English Shepherd                   unknown                     3     3         3            3               0               3               3      3         3
           English Springer Spaniel           SPORTING GROUP              8     7         8            8               3               8               8      8         8
           Entlebucher                        unknown                     1     1         1            1               1               1               1      1         1
           Feist                              unknown                     6     6         6            6               1               6               6      6         6
           Field Spaniel                      SPORTING GROUP              2     2         2            2               1               2               2      2         2
           Finnish Spitz                      unknown                    11    11        11           11               4              11              11     11        11
           Flat Coat Retriever                unknown                    48    38        48           48              19              48              48     48        48
           French Bulldog                     NON-SPORTING GROUP         11     9        11           11               3              11              11     11        11
           German Pinscher                    WORKING GROUP               2     2         2            2               2               2               2      2         2

In [50]:
def BreedMix(x):
    if '/' in  x:
        g
        return 1
    elif 'Mix' in x:
        return 1
    else:
        return 0

df_all['BreedMix'] = df_all['Breed'].apply(BreedMix)

def Nature_Breed(x):
    if '/' in x:
        x = x[0:x.index('/')]
        return x
    elif ' Mix' in x:
        x = x[0:-4]
        return x
    else:
        return x

df_all['Breed'] = df_all['Breed'].apply(Nature_Breed)