In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from pandas import DataFrame, Series
from sklearn.preprocessing import LabelEncoder
from sklearn import preprocessing
%matplotlib inline

pd.set_option('display.max_rows', 30000)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

df = pd.read_csv('C:/chwweww/dss6_out/sin/train.csv')
print(np.shape(df))
df.tail()

(26729, 10)

      AnimalID  Name             DateTime OutcomeType OutcomeSubtype AnimalType SexuponOutcome AgeuponOutcome                    Breed              Color
26724  A702446   NaN  2015-05-14 11:56:00    Transfer        Partner        Cat    Intact Male        1 month   Domestic Shorthair Mix  Brown Tabby/White
26725  A718934   NaN  2016-01-20 18:59:00    Transfer           SCRP        Cat  Spayed Female       3 months   Domestic Shorthair Mix        Brown Tabby
26726  A698128  Zeus  2015-03-09 13:33:00    Adoption            NaN        Dog  Neutered Male        4 years  Old English Bulldog Mix          White/Tan
26727  A677478   NaN  2014-04-27 12:22:00    Transfer        Partner        Cat    Intact Male        4 weeks   Domestic Shorthair Mix              Black
26728  A706629   NaN  2015-07-02 09:00:00    Transfer           SCRP        Cat    Intact Male         1 year   Domestic Shorthair Mix  Brown Tabby/White

In [2]:
df1 = df

In [3]:
def BreedMix(x):
    if '/' in  x:
        return 1
    elif 'Mix' in x:
        return 1
    else:
        return 0

df1['BreedMix'] = df1['Breed'].apply(BreedMix)

def Nature_Breed(x):
    if '/' in x:
        x = x[0:x.index('/')]
        return x
    elif ' Mix' in x:
        x = x[0:-4]
        return x
    else:
        return x

df1['Breed'] = df1['Breed'].apply(Nature_Breed)

In [4]:
from bs4 import BeautifulSoup
import requests
import pandas as pd


info_url = 'http://www.akc.org/public-education/resources/dog-breeds-sorted-groups/'
response = requests.get(info_url)
soup = BeautifulSoup(response.content.decode('latin1'), 'lxml')
breed_group = list()
group_element = list()

groups = soup.select('h2')
for group in groups:
    breed_group.append(group.get_text())


group_element = breed_group
group_element

['HERDING GROUP',
 'HOUND GROUP',
 'TOY GROUP',
 'NON-SPORTING GROUP',
 'SPORTING GROUP',
 'TERRIER GROUP',
 'WORKING GROUP',
 'MISCELLANEOUS CLASS']

In [5]:
group_lists = soup.select('ol')

dog_list = list()
for num,group_list in enumerate(group_lists):
    group_lst = group_list.select('li')
    breed_group[num] = list()
    for dog_breeds in group_lst:
        dog_breed = dog_breeds.find('a')
        breed_group[num].append(dog_breed.get_text())

Catahoula -> CATAHOULA LEOPARD DOG (Herding Group)

Chihuahua Shorthair -> CHIHUAHUA (Toy Group)

German Shepherd -> GERMAN SHEPHERD DOG (Herding Group)

Jack Russell Terrier -> RUSSELL TERRIER (Terrier Group)

Miniature Poodle -> POODLE (Non Sporting Group)

Pit Bull -> Pit Bull Terrier (Terrier Group)

Domestic Shorthair : cat1

Domestic Medium Hair : cat2

Domestic Longhair : cat3

Siamese : cat4

In [6]:
breed_group[0]

['Australian Cattle Dog',
 'Australian Shepherd',
 'Bearded Collie',
 'Beauceron',
 'Belgian Malinois',
 'Belgian Sheepdog',
 'Belgian Tervuren',
 'Bergamasco',
 'Berger Picard',
 'Border Collie',
 'Bouvier des Flandres',
 'Briard',
 'Canaan Dog',
 'Cardigan Welsh Corgi',
 'Collie',
 'Entlebucher Moutain Dog',
 'Finnish Lapphund',
 'German Shepherd Dog',
 'Icelandic Sheepdog',
 'Miniature American Shepherd',
 'Norwegian Buhund',
 'Old English Sheepdog',
 'Pembroke Welsh Corgi',
 'Polish Lowland Sheepdog',
 'Puli',
 'Pumi',
 'Pyrenean Sheepdog',
 'Shetland Sheepdog',
 'Spanish Water Dog',
 'Swedish Vallhund']

In [7]:
breed_group[0]

['Australian Cattle Dog',
 'Australian Shepherd',
 'Bearded Collie',
 'Beauceron',
 'Belgian Malinois',
 'Belgian Sheepdog',
 'Belgian Tervuren',
 'Bergamasco',
 'Berger Picard',
 'Border Collie',
 'Bouvier des Flandres',
 'Briard',
 'Canaan Dog',
 'Cardigan Welsh Corgi',
 'Collie',
 'Entlebucher Moutain Dog',
 'Finnish Lapphund',
 'German Shepherd Dog',
 'Icelandic Sheepdog',
 'Miniature American Shepherd',
 'Norwegian Buhund',
 'Old English Sheepdog',
 'Pembroke Welsh Corgi',
 'Polish Lowland Sheepdog',
 'Puli',
 'Pumi',
 'Pyrenean Sheepdog',
 'Shetland Sheepdog',
 'Spanish Water Dog',
 'Swedish Vallhund']

In [8]:
breed_group[0].append('Catahoula')
breed_group[0].append('German Shepherd')
breed_group[2].append('Chihuahua Shorthair')
breed_group[3].append('Miniature Poodle')
breed_group[5].append('Jack Russell Terrier')
breed_group[5].append('Pit Bull')

In [9]:
df_HERDING = pd.DataFrame(breed_group[0], columns=['Breed'])
df_HERDING["GROUP"] = "HERDING GROUP"

df_HOUND = pd.DataFrame(breed_group[1], columns=['Breed'])
df_HOUND["GROUP"] = "HOUND GROUP"

df_TOY = pd.DataFrame(breed_group[2], columns=['Breed'])
df_TOY["GROUP"] = "TOY GROUP"

df_NON_SPORTING = pd.DataFrame(breed_group[3] , columns=['Breed'])
df_NON_SPORTING["GROUP"] = "NON-SPORTING GROUP"

df_SPORTING = pd.DataFrame(breed_group[4], columns=['Breed'])
df_SPORTING["GROUP"] = "SPORTING GROUP"

df_TERRIER = pd.DataFrame(breed_group[5], columns=['Breed'])
df_TERRIER["GROUP"] = "TERRIER GROUP"

df_WORKING = pd.DataFrame(breed_group[6], columns=['Breed'])
df_WORKING["GROUP"] = "WORKING GROUP"

df_MISCELLANEOUS = pd.DataFrame(breed_group[7], columns=['Breed'])
df_MISCELLANEOUS["GROUP"] = "MISCELLANEOUS CLASS"

In [44]:
df_cat1 = pd.DataFrame({'Breed' : ['Domestic Shorthair'],'GROUP': ['cat1']})
df_cat2 = pd.DataFrame({'Breed' : ['Domestic Medium Hair'],'GROUP': ['cat2']})
df_cat3 = pd.DataFrame({'Breed' : ['Domestic Longhair'],'GROUP': ['cat3']})
df_cat4 = pd.DataFrame({'Breed' : ['Siamese'],'GROUP': ['cat4']})

In [46]:
df_group_all = pd.concat([df_HERDING, df_HOUND ,df_TOY ,df_NON_SPORTING , df_SPORTING ,df_TERRIER , df_WORKING , df_MISCELLANEOUS , df_cat1 , df_cat2 , df_cat3 , df_cat4], axis=0, ignore_index=True)
df_group_all

                                  Breed                GROUP
0                 Australian Cattle Dog        HERDING GROUP
1                   Australian Shepherd        HERDING GROUP
2                        Bearded Collie        HERDING GROUP
3                             Beauceron        HERDING GROUP
4                      Belgian Malinois        HERDING GROUP
5                      Belgian Sheepdog        HERDING GROUP
6                      Belgian Tervuren        HERDING GROUP
7                            Bergamasco        HERDING GROUP
8                         Berger Picard        HERDING GROUP
9                         Border Collie        HERDING GROUP
10                 Bouvier des Flandres        HERDING GROUP
11                               Briard        HERDING GROUP
12                           Canaan Dog        HERDING GROUP
13                 Cardigan Welsh Corgi        HERDING GROUP
14                               Collie        HERDING GROUP
15              Entlebucher Moutain Dog        HERDING GROUP
16                     Finnish Lapphund        HERDING GROUP
17                  German Shepherd Dog        HERDING GROUP
18                   Icelandic Sheepdog        HERDING GROUP
19          Miniature American Shepherd        HERDING GROUP
20                     Norwegian Buhund        HERDING GROUP
21                 Old English Sheepdog        HERDING GROUP
22                 Pembroke Welsh Corgi        HERDING GROUP
23              Polish Lowland Sheepdog        HERDING GROUP
24                                 Puli        HERDING GROUP
25                                 Pumi        HERDING GROUP
26                    Pyrenean Sheepdog        HERDING GROUP
27                    Shetland Sheepdog        HERDING GROUP
28                    Spanish Water Dog        HERDING GROUP
29                     Swedish Vallhund        HERDING GROUP
30                            Catahoula        HERDING GROUP
31                      German Shepherd        HERDING GROUP
32                         Afghan Hound          HOUND GROUP
33           American English Coonhound          HOUND GROUP
34                    American Foxhound          HOUND GROUP
35                              Basenji          HOUND GROUP
36                         Basset Hound          HOUND GROUP
37                               Beagle          HOUND GROUP
38              Black and Tan Coonhound          HOUND GROUP
39                           Bloodhound          HOUND GROUP
40                   Bluetick Coonhound          HOUND GROUP
41                               Borzoi          HOUND GROUP
42                    Cirneco Dell’Etna          HOUND GROUP
43                            Dachshund          HOUND GROUP
44                     English Foxhound          HOUND GROUP
45                            Greyhound          HOUND GROUP
46                              Harrier          HOUND GROUP
47                         Ibizan Hound          HOUND GROUP
48                      Irish Wolfhound          HOUND GROUP
49                   Norwegian Elkhound          HOUND GROUP
50                           Otterhound          HOUND GROUP
51         Petit Basset Griffon Vendeen          HOUND GROUP
52                        Pharaoh Hound          HOUND GROUP
53                                Plott          HOUND GROUP
54           Portuguese Podengo Pequeno          HOUND GROUP
55                    Redbone Coonhound          HOUND GROUP
56                  Rhodesian Ridgeback          HOUND GROUP
57                               Saluki          HOUND GROUP
58                   Scottish Deerhound          HOUND GROUP
59                              Sloughi          HOUND GROUP
60             Treeing Walker Coonhound          HOUND GROUP
61                              Whippet          HOUND GROUP
62                        Affenpinscher            TOY GROUP
63                     Brussels Griffon            TOY GROUP
64        Cavalier King Charles Spaniel            TOY GROUP
65                            Chihuahua            TOY GROUP
66                      Chinese Crested            TOY GROUP
67                  English Toy Spaniel            TOY GROUP
68                             Havanese            TOY GROUP
69                    Italian Greyhound            TOY GROUP
70                        Japanese Chin            TOY GROUP
71                              Maltese            TOY GROUP
72                   Manchester Terrier            TOY GROUP
73                   Miniature Pinscher            TOY GROUP
74                             Papillon            TOY GROUP
75                            Pekingese            TOY GROUP
76                           Pomeranian            TOY GROUP
77                         Poodle (Toy)            TOY GROUP
78                                  Pug            TOY GROUP
79                             Shih Tzu            TOY GROUP
80                        Silky Terrier            TOY GROUP
81                      Toy Fox Terrier            TOY GROUP
82                    Yorkshire Terrier            TOY GROUP
83                  Chihuahua Shorthair            TOY GROUP
84                  American Eskimo Dog   NON-SPORTING GROUP
85                         Bichon Frise   NON-SPORTING GROUP
86                       Boston Terrier   NON-SPORTING GROUP
87                              Bulldog   NON-SPORTING GROUP
88                     Chinese Shar-Pei   NON-SPORTING GROUP
89                            Chow Chow   NON-SPORTING GROUP
90                      Coton De Tulear   NON-SPORTING GROUP
91                            Dalmatian   NON-SPORTING GROUP
92                         Finish Spitz   NON-SPORTING GROUP
93                       French Bulldog   NON-SPORTING GROUP
94                             Keeshond   NON-SPORTING GROUP
95                           Lhasa Apso   NON-SPORTING GROUP
96                              Lowchen   NON-SPORTING GROUP
97                   Norwegian Lundhund   NON-SPORTING GROUP
98                               Poodle   NON-SPORTING GROUP
99                           Schipperke   NON-SPORTING GROUP
100                           Shiba Inu   NON-SPORTING GROUP
101                     Tibetan Spaniel   NON-SPORTING GROUP
102                     Tibetan Terrier   NON-SPORTING GROUP
103                      Xoloitzcuintli   NON-SPORTING GROUP
104                    Miniature Poodle   NON-SPORTING GROUP
105              American Water Spaniel       SPORTING GROUP
106                      Boykin Spaniel       SPORTING GROUP
107                            Brittany       SPORTING GROUP
108            Chesapeake Bay Retriever       SPORTING GROUP
109                     Clumber Spaniel       SPORTING GROUP
110                      Cocker Spaniel       SPORTING GROUP
111              Curly-Coated Retriever       SPORTING GROUP
112              English Cocker Spaniel       SPORTING GROUP
113                      English Setter       SPORTING GROUP
114            English Springer Spaniel       SPORTING GROUP
115                       Field Spaniel       SPORTING GROUP
116               Flat-Coated Retriever       SPORTING GROUP
117          German Shorthaired Pointer       SPORTING GROUP
118           German Wirehaired Pointer       SPORTING GROUP
119                    Golden Retriever       SPORTING GROUP
120                       Gordon Setter       SPORTING GROUP
121          Irish Red and White Setter       SPORTING GROUP
122                        Irish Setter       SPORTING GROUP
123                 Irish Water Spaniel       SPORTING GROUP
124                  Labrador Retriever       SPORTING GROUP
125                   Lagotto Romagnolo       SPORTING GROUP
126  Nova Scotia Duck Tolling Retriever       SPORTING GROUP
127                             Pointer       SPORTING GROUP
128                    Spinone Italiano       SPORTING GROUP
129                      Sussex Spaniel       SPORTING GROUP
130                              Vizsla       SPORTING GROUP
131                          Weimaraner       SPORTING GROUP
132              Welsh Springer Spaniel       SPORTING GROUP
133         Wirehaired Pointing Griffon       SPORTING GROUP
134                   Wirehaired Vizsla       SPORTING GROUP
135                    Airedale Terrier        TERRIER GROUP
136           American Hairless Terrier        TERRIER GROUP
137      American Staffordshire Terrier        TERRIER GROUP
138                  Australian Terrier        TERRIER GROUP
139                  Bedlington Terrier        TERRIER GROUP
140                      Border Terrier        TERRIER GROUP
141                        Bull Terrier        TERRIER GROUP
142                       Cairn Terrier        TERRIER GROUP
143                       Cesky Terrier        TERRIER GROUP
144              Dandie Dinmont Terrier        TERRIER GROUP
145               Glen of Imaal Terrier        TERRIER GROUP
146                       Irish Terrier        TERRIER GROUP
147                  Kerry Blue Terrier        TERRIER GROUP
148                    Lakeland Terrier        TERRIER GROUP
149                  Manchester Terrier        TERRIER GROUP
150              Miniature Bull Terrier        TERRIER GROUP
151                 Miniature Schnauzer        TERRIER GROUP
152                     Norfolk Terrier        TERRIER GROUP
153                     Norwich Terrier        TERRIER GROUP
154              Parson Russell Terrier        TERRIER GROUP
155                         Rat Terrier        TERRIER GROUP
156                     Russell Terrier        TERRIER GROUP
157                    Scottish Terrier        TERRIER GROUP
158                    Sealyham Terrier        TERRIER GROUP
159                        Skye Terrier        TERRIER GROUP
160                  Smooth Fox Terrier        TERRIER GROUP
161          Staffordshire Bull Terrier        TERRIER GROUP
162                       Welsh Terrier        TERRIER GROUP
163         West Highland White Terrier        TERRIER GROUP
164                    Wire Fox Terrier        TERRIER GROUP
165                Jack Russell Terrier        TERRIER GROUP
166                            Pit Bull        TERRIER GROUP
167                               Akita        WORKING GROUP
168                    Alaskan Malamute        WORKING GROUP
169              Anatolian Shepherd Dog        WORKING GROUP
170                Bernese Mountain Dog        WORKING GROUP
171               Black Russian Terrier        WORKING GROUP
172                            Boerboel        WORKING GROUP
173                               Boxer        WORKING GROUP
174                         Bullmastiff        WORKING GROUP
175                          Cane Corso        WORKING GROUP
176                             Chinook        WORKING GROUP
177                   Doberman Pinscher        WORKING GROUP
178                   Dogue de Bordeaux        WORKING GROUP
179                     German Pinscher        WORKING GROUP
180                     Giant Schnauzer        WORKING GROUP
181                          Great Dane        WORKING GROUP
182                      Great Pyrenees        WORKING GROUP
183          Greater Swiss Mountain Dog        WORKING GROUP
184                            Komondor        WORKING GROUP
185                              Kuvasz        WORKING GROUP
186                          Leonberger        WORKING GROUP
187                             Mastiff        WORKING GROUP
188                  Neapolitan Mastiff        WORKING GROUP
189                        Newfoundland        WORKING GROUP
190                Portuguese Water Dog        WORKING GROUP
191                          Rottweiler        WORKING GROUP
192                             Samoyed        WORKING GROUP
193                      Siberian Husky        WORKING GROUP
194                  Standard Schnauzer        WORKING GROUP
195                     Tibetan Mastiff        WORKING GROUP
196                         St. Bernard        WORKING GROUP
197                             Azawakh  MISCELLANEOUS CLASS
198                   Belgian Laekenois  MISCELLANEOUS CLASS
199                      Dogo Argentino  MISCELLANEOUS CLASS
200        Grand Basset Griffon Vendeen  MISCELLANEOUS CLASS
201           Nederlandse Kooikerhondje  MISCELLANEOUS CLASS
202                     Norrbottenspets  MISCELLANEOUS CLASS
203                Peruvian Inca Orchid  MISCELLANEOUS CLASS
204                  Portuguese Podengo  MISCELLANEOUS CLASS
205                  Domestic Shorthair                 cat1
206                Domestic Medium Hair                 cat2
207                   Domestic Longhair                 cat3
208                             Siamese                 cat4

In [12]:
df1 = df

In [47]:
df_group_all = df_group_all.drop(72)

In [48]:
df_all_1 = pd.merge(df1 , df_group_all , how = 'left')

In [49]:
df_group_all['Breed'].value_counts()

Wirehaired Pointing Griffon           1
Bernese Mountain Dog                  1
Dandie Dinmont Terrier                1
Affenpinscher                         1
Akita                                 1
Peruvian Inca Orchid                  1
Keeshond                              1
Beagle                                1
Field Spaniel                         1
Flat-Coated Retriever                 1
Weimaraner                            1
Boston Terrier                        1
Mastiff                               1
Collie                                1
Border Terrier                        1
Golden Retriever                      1
St. Bernard                           1
Chinese Shar-Pei                      1
Old English Sheepdog                  1
Cesky Terrier                         1
Pumi                                  1
Irish Wolfhound                       1
Sussex Spaniel                        1
Nederlandse Kooikerhondje             1
Belgian Sheepdog                      1
Redbone Coonhound                     1
Rhodesian Ridgeback                   1
Chinook                               1
Neapolitan Mastiff                    1
Domestic Medium Hair                  1
Tibetan Mastiff                       1
Anatolian Shepherd Dog                1
Shiba Inu                             1
Italian Greyhound                     1
Plott                                 1
Sloughi                               1
German Pinscher                       1
American Hairless Terrier             1
Rottweiler                            1
Giant Schnauzer                       1
Cane Corso                            1
Finnish Lapphund                      1
Alaskan Malamute                      1
Bearded Collie                        1
Wire Fox Terrier                      1
Shih Tzu                              1
American Foxhound                     1
Belgian Laekenois                     1
Irish Red and White Setter            1
Newfoundland                          1
American Staffordshire Terrier        1
Samoyed                               1
Puli                                  1
Labrador Retriever                    1
Pekingese                             1
Scottish Terrier                      1
Bull Terrier                          1
Wirehaired Vizsla                     1
Gordon Setter                         1
Saluki                                1
Brussels Griffon                      1
American Eskimo Dog                   1
Chow Chow                             1
Japanese Chin                         1
Azawakh                               1
Pomeranian                            1
Brittany                              1
Xoloitzcuintli                        1
Boxer                                 1
Lakeland Terrier                      1
Bulldog                               1
Leonberger                            1
Belgian Tervuren                      1
Tibetan Spaniel                       1
Basenji                               1
Cairn Terrier                         1
Boerboel                              1
Black and Tan Coonhound               1
Bloodhound                            1
Lowchen                               1
Dogue de Bordeaux                     1
Norrbottenspets                       1
Otterhound                            1
Pit Bull                              1
Chinese Crested                       1
Silky Terrier                         1
Irish Setter                          1
Domestic Longhair                     1
English Foxhound                      1
Cocker Spaniel                        1
Coton De Tulear                       1
Komondor                              1
Spinone Italiano                      1
Harrier                               1
Toy Fox Terrier                       1
Tibetan Terrier                       1
Bedlington Terrier                    1
English Springer Spaniel              1
Pembroke Welsh Corgi                  1
Maltese                               1
Havanese                              1
German Shepherd                       1
Miniature Bull Terrier                1
Australian Shepherd                   1
Great Dane                            1
Australian Terrier                    1
Standard Schnauzer                    1
Miniature Pinscher                    1
Dalmatian                             1
Manchester Terrier                    1
English Cocker Spaniel                1
Siberian Husky                        1
German Wirehaired Pointer             1
Siamese                               1
Bullmastiff                           1
Staffordshire Bull Terrier            1
English Toy Spaniel                   1
Finish Spitz                          1
Norwegian Buhund                      1
Canaan Dog                            1
Jack Russell Terrier                  1
Whippet                               1
Kerry Blue Terrier                    1
English Setter                        1
Norfolk Terrier                       1
Pharaoh Hound                         1
Norwich Terrier                       1
Rat Terrier                           1
Pug                                   1
Portuguese Podengo Pequeno            1
Poodle                                1
Skye Terrier                          1
Petit Basset Griffon Vendeen          1
Kuvasz                                1
Shetland Sheepdog                     1
Norwegian Lundhund                    1
Lhasa Apso                            1
Cirneco Dell’Etna                     1
Miniature Poodle                      1
Chihuahua                             1
Norwegian Elkhound                    1
Great Pyrenees                        1
Schipperke                            1
Vizsla                                1
Ibizan Hound                          1
Australian Cattle Dog                 1
Cardigan Welsh Corgi                  1
Domestic Shorthair                    1
Border Collie                         1
Borzoi                                1
Basset Hound                          1
Bichon Frise                          1
Parson Russell Terrier                1
Afghan Hound                          1
Pyrenean Sheepdog                     1
Irish Water Spaniel                   1
Welsh Terrier                         1
Miniature Schnauzer                   1
Scottish Deerhound                    1
Welsh Springer Spaniel                1
Black Russian Terrier                 1
Papillon                              1
Dogo Argentino                        1
Polish Lowland Sheepdog               1
American English Coonhound            1
Entlebucher Moutain Dog               1
Boykin Spaniel                        1
Portuguese Water Dog                  1
Smooth Fox Terrier                    1
Greater Swiss Mountain Dog            1
West Highland White Terrier           1
American Water Spaniel                1
Chihuahua Shorthair                   1
Lagotto Romagnolo                     1
Berger Picard                         1
Curly-Coated Retriever                1
Irish Terrier                         1
Nova Scotia Duck Tolling Retriever    1
German Shepherd Dog                   1
Chesapeake Bay Retriever              1
Yorkshire Terrier                     1
Portuguese Podengo                    1
Russell Terrier                       1
Airedale Terrier                      1
Beauceron                             1
Miniature American Shepherd           1
Catahoula                             1
Greyhound                             1
Spanish Water Dog                     1
Belgian Malinois                      1
Bouvier des Flandres                  1
Cavalier King Charles Spaniel         1
Clumber Spaniel                       1
Icelandic Sheepdog                    1
German Shorthaired Pointer            1
Doberman Pinscher                     1
Glen of Imaal Terrier                 1
Treeing Walker Coonhound              1
Bluetick Coonhound                    1
Sealyham Terrier                      1
Swedish Vallhund                      1
French Bulldog                        1
Dachshund                             1
Pointer                               1
Briard                                1
Poodle (Toy)                          1
Grand Basset Griffon Vendeen          1
Bergamasco                            1
Name: Breed, dtype: int64

In [50]:
df_all_1.tail()

      AnimalID  Name             DateTime OutcomeType OutcomeSubtype AnimalType SexuponOutcome AgeuponOutcome                Breed              Color  BreedMix GROUP
26724  A702446   NaN  2015-05-14 11:56:00    Transfer        Partner        Cat    Intact Male        1 month   Domestic Shorthair  Brown Tabby/White         1  cat1
26725  A718934   NaN  2016-01-20 18:59:00    Transfer           SCRP        Cat  Spayed Female       3 months   Domestic Shorthair        Brown Tabby         1  cat1
26726  A698128  Zeus  2015-03-09 13:33:00    Adoption            NaN        Dog  Neutered Male        4 years  Old English Bulldog          White/Tan         1   NaN
26727  A677478   NaN  2014-04-27 12:22:00    Transfer        Partner        Cat    Intact Male        4 weeks   Domestic Shorthair              Black         1  cat1
26728  A706629   NaN  2015-07-02 09:00:00    Transfer           SCRP        Cat    Intact Male         1 year   Domestic Shorthair  Brown Tabby/White         1  cat1

In [51]:
print(df_all_1.shape)

(26729, 12)

In [52]:
df_all_1.groupby([ 'AnimalType' , 'GROUP']).count()

                                AnimalID  Name  DateTime  OutcomeType  OutcomeSubtype  SexuponOutcome  AgeuponOutcome  Breed  Color  BreedMix
AnimalType GROUP
Cat        cat1                     8958  4741      8958         8958            6130            8958            8942   8958   8958      8958
           cat2                      883   517       883          883             606             883             883    883    883       883
           cat3                      547   351       547          547             339             547             546    547    547       547
           cat4                      426   262       426          426             260             426             426    426    426       426
Dog        HERDING GROUP            2319  1926      2319         2319             763            2319            2319   2319   2319      2319
           HOUND GROUP               947   782       947          947             338             946             947    947    947       947
           MISCELLANEOUS CLASS        17    17        17           17              10              17              17     17     17        17
           NON-SPORTING GROUP        653   519       653          653             227             653             653    653    653       653
           SPORTING GROUP           2329  1895      2329         2329             818            2329            2329   2329   2329      2329
           TERRIER GROUP            3282  2777      3282         3282            1244            3282            3282   3282   3282      3282
           TOY GROUP                3041  2456      3041         3041            1200            3041            3041   3041   3041      3041
           WORKING GROUP            1059   938      1059         1059             345            1059            1059   1059   1059      1059

In [53]:
df_jo = df_all_1.copy()

In [54]:
df_jo['GROUP'].fillna("unknown", inplace=True)

In [55]:
df_jo.groupby(['AnimalType', 'GROUP', 'Breed']).count()

                                                                   AnimalID  Name  DateTime  OutcomeType  OutcomeSubtype  SexuponOutcome  AgeuponOutcome  Color  BreedMix
AnimalType GROUP               Breed
Cat        cat1                Domestic Shorthair                      8958  4741      8958         8958            6130            8958            8942   8958      8958
           cat2                Domestic Medium Hair                     883   517       883          883             606             883             883    883       883
           cat3                Domestic Longhair                        547   351       547          547             339             547             546    547       547
           cat4                Siamese                                  426   262       426          426             260             426             426    426       426
           unknown             Abyssinian                                 2     2         2            2               0               2               2      2         2
                               American Shorthair                         9     6         9            9               8               9               9      9         9
                               Angora                                     7     5         7            7               3               7               7      7         7
                               Balinese                                   5     5         5            5               4               5               5      5         5
                               Bengal                                     5     4         5            5               1               5               5      5         5
                               Bombay                                     5     5         5            5               1               5               5      5         5
                               British Shorthair                          4     4         4            4               2               4               4      4         4
                               Burmese                                    1     0         1            1               0               1               1      1         1
                               Cornish Rex                                1     1         1            1               0               1               1      1         1
                               Cymric                                     2     2         2            2               2               2               2      2         2
                               Devon Rex                                  2     2         2            2               1               2               2      2         2
                               Exotic Shorthair                           2     2         2            2               2               2               2      2         2
                               Havana Brown                               1     1         1            1               1               1               1      1         1
                               Himalayan                                 18    12        18           18              10              18              18     18        18
                               Japanese Bobtail                           6     5         6            6               4               6               6      6         6
                               Javanese                                   2     2         2            2               0               2               2      2         2
                               Maine Coon                                47    39        47           47              23              47              47     47        47
                               Manx                                      48    34        48           48              27              48              48     48        48
                               Munchkin Longhair                          1     0         1            1               1               1               1      1         1
                               Norwegian Forest Cat                       1     1         1            1               1               1               1      1         1
                               Ocicat                                     1     1         1            1               0               1               1      1         1
                               Persian                                   14    10        14           14               7              14              14     14        14
                               Pixiebob Shorthair                         3     3         3            3               2               3               3      3         3
                               Ragdoll                                   12     6        12           12               9              12              12     12        12
                               Russian Blue                              35    28        35           35              17              35              35     35        35
                               Snowshoe                                  78    58        78           78              45              78              78     78        78
                               Sphynx                                     2     2         2            2               1               2               2      2         2
                               Tonkinese                                  4     2         4            4               3               4               4      4         4
                               Turkish Van                                2     2         2            2               1               2               2      2         2
Dog        HERDING GROUP       Australian Cattle Dog                    511   424       511          511             177             511             511    511       511
                               Australian Shepherd                      229   184       229          229              71             229             229    229       229
                               Bearded Collie                             2     2         2            2               1               2               2      2         2
                               Beauceron                                 12    10        12           12               6              12              12     12        12
                               Belgian Malinois                          18    15        18           18               5              18              18     18        18
                               Belgian Sheepdog                           3     2         3            3               0               3               3      3         3
                               Belgian Tervuren                           2     2         2            2               2               2               2      2         2
                               Border Collie                            334   283       334          334             111             334             334    334       334
                               Canaan Dog                                 5     5         5            5               2               5               5      5         5
                               Cardigan Welsh Corgi                      84    67        84           84              29              84              84     84        84
                               Catahoula                                218   190       218          218              77             218             218    218       218
                               German Shepherd                          826   680       826          826             260             826             826    826       826
                               Old English Sheepdog                       2     1         2            2               1               2               2      2         2
                               Pembroke Welsh Corgi                      30    25        30           30               5              30              30     30        30
                               Shetland Sheepdog                         37    30        37           37              16              37              37     37        37
                               Swedish Vallhund                           6     6         6            6               0               6               6      6         6
           HOUND GROUP         Afghan Hound                               1     1         1            1               0               1               1      1         1
                               American Foxhound                          5     5         5            5               0               5               5      5         5
                               Basenji                                   18    18        18           18               5              18              18     18        18
                               Basset Hound                              71    65        71           71              15              71              71     71        71
                               Beagle                                   220   190       220          220              65             220             220    220       220
                               Bloodhound                                 8     7         8            8               1               8               8      8         8
                               Dachshund                                510   395       510          510             209             509             510    510       510
                               English Foxhound                           3     3         3            3               1               3               3      3         3
                               Greyhound                                 18    18        18           18               7              18              18     18        18
                               Harrier                                   21    20        21           21               9              21              21     21        21
                               Ibizan Hound                               3     3         3            3               0               3               3      3         3
                               Irish Wolfhound                            6     6         6            6               2               6               6      6         6
                               Norwegian Elkhound                         1     1         1            1               0               1               1      1         1
                               Otterhound                                 1     1         1            1               0               1               1      1         1
                               Pharaoh Hound                             13    13        13           13               4              13              13     13        13
                               Saluki                                     5     5         5            5               2               5               5      5         5
                               Treeing Walker Coonhound                   9     7         9            9               5               9               9      9         9
                               Whippet                                   34    24        34           34              13              34              34     34        34
           MISCELLANEOUS CLASS Dogo Argentino                            17    17        17           17              10              17              17     17        17
           NON-SPORTING GROUP  Bichon Frise                              20    14        20           20               3              20              20     20        20
                               Boston Terrier                            67    50        67           67              25              67              67     67        67
                               Bulldog                                   14    14        14           14               2              14              14     14        14
                               Chow Chow                                 95    72        95           95              41              95              95     95        95
                               Dalmatian                                 17    15        17           17               3              17              17     17        17
                               French Bulldog                            11     9        11           11               3              11              11     11        11
                               Keeshond                                   6     4         6            6               2               6               6      6         6
                               Lhasa Apso                                70    57        70           70              45              70              70     70        70
                               Lowchen                                    1     1         1            1               0               1               1      1         1
                               Miniature Poodle                         310   246       310          310              93             310             310    310       310
                               Schipperke                                 9     9         9            9               2               9               9      9         9
                               Shiba Inu                                 21    18        21           21               5              21              21     21        21
                               Tibetan Spaniel                            4     4         4            4               1               4               4      4         4
                               Tibetan Terrier                            8     6         8            8               2               8               8      8         8
           SPORTING GROUP      Brittany                                  11    11        11           11               2              11              11     11        11
                               Cocker Spaniel                            84    66        84           84              34              84              84     84        84
                               English Cocker Spaniel                     1     1         1            1               1               1               1      1         1
                               English Setter                             2     2         2            2               1               2               2      2         2
                               English Springer Spaniel                   8     7         8            8               3               8               8      8         8
                               Field Spaniel                              2     2         2            2               1               2               2      2         2
                               German Wirehaired Pointer                  5     4         5            5               1               5               5      5         5
                               Golden Retriever                         107    95       107          107              32             107             107    107       107
                               Irish Setter                               3     3         3            3               3               3               3      3         3
                               Labrador Retriever                      1915  1546      1915         1915             674            1915            1915   1915      1915
                               Nova Scotia Duck Tolling Retriever         3     2         3            3               1               3               3      3         3
                               Pointer                                  139   116       139          139              51             139             139    139       139
                               Spinone Italiano                           1     1         1            1               0               1               1      1         1
                               Vizsla                                    17    16        17           17               1              17              17     17        17
                               Weimaraner                                27    19        27           27              12              27              27     27        27
                               Welsh Springer Spaniel                     2     2         2            2               1               2               2      2         2
                               Wirehaired Pointing Griffon                2     2         2            2               0               2               2      2         2
           TERRIER GROUP       Airedale Terrier                           8     7         8            8               4               8               8      8         8
                               American Staffordshire Terrier           110    99       110          110              37             110             110    110       110
                               Australian Terrier                         4     3         4            4               0               4               4      4         4
                               Border Terrier                            53    43        53           53              12              53              53     53        53
                               Bull Terrier                              38    33        38           38              16              38              38     38        38
                               Cairn Terrier                            142    97       142          142              47             142             142    142       142
                               Irish Terrier                              6     4         6            6               2               6               6      6         6
                               Jack Russell Terrier                     222   177       222          222              69             222             222    222       222
                               Manchester Terrier                        56    46        56           56              18              56              56     56        56
                               Miniature Schnauzer                      220   174       220          220              57             220             220    220       220
                               Norfolk Terrier                           30    22        30           30               6              30              30     30        30
                               Norwich Terrier                           18    13        18           18               6              18              18     18        18
                               Parson Russell Terrier                    23    21        23           23               5              23              23     23        23
                               Pit Bull                                2113  1847      2113         2113             877            2113            2113   2113      2113
                               Rat Terrier                              215   170       215          215              80             215             215    215       215
                               Scottish Terrier                           5     5         5            5               2               5               5      5         5
                               Skye Terrier                               4     3         4            4               2               4               4      4         4

In [56]:
print(df_jo.shape)

(26729, 12)

In [57]:
print(df.shape)

(26729, 11)